parameters:
    ongr_task_messenger.amqp_connection.class: PhpAmqpLib\Connection\AMQPConnection
    ongr_task_messenger.amqp_connection.host: localhost
    ongr_task_messenger.amqp_connection.port: 5672
    ongr_task_messenger.amqp_connection.user: guest
    ongr_task_messenger.amqp_connection.password: guest

    ongr_task_messenger.beanstalkd_connection.class: Pheanstalk\Pheanstalk
    ongr_task_messenger.beanstalkd_connection.host: localhost
    ongr_task_messenger.beanstalkd_connection.port: 11300

    ongr_task_messenger.connection_factory.class: ONGR\TaskMessengerBundle\Publishers\ConnectionFactory
    ongr_task_messenger.task_publisher.class: ONGR\TaskMessengerBundle\Service\TaskPublisher

    ongr_task_messenger.task_publisher.amqp.class: ONGR\TaskMessengerBundle\Publishers\AMQPPublisher
    ongr_task_messenger.task_publisher.amqp.enabled: true
    ongr_task_messenger.task_publisher.beanstalkd.class: ONGR\TaskMessengerBundle\Publishers\BeanstalkdPublisher
    ongr_task_messenger.task_publisher.beanstalkd.enabled: true

    ongr_task_messenger.sync_task_complete_listener.class: ONGR\TaskMessengerBundle\Service\SyncTasksListener

    ongr_task_messenger.logger.class: Symfony\Component\HttpKernel\Log\NullLogger

services:
    ongr_task_messenger.task_publisher:
        class: %ongr_task_messenger.task_publisher.class%

    ongr_task_messenger.amqp_connection_factory:
        class: %ongr_task_messenger.connection_factory.class%
        arguments:
            - %ongr_task_messenger.amqp_connection.class%
            - %ongr_task_messenger.amqp_connection.host%
            - %ongr_task_messenger.amqp_connection.port%
            - %ongr_task_messenger.amqp_connection.user%
            - %ongr_task_messenger.amqp_connection.password%
    ongr_task_messenger.task_publisher.amqp:
        class: %ongr_task_messenger.task_publisher.amqp.class%
        arguments:
            - @ongr_task_messenger.amqp_connection_factory
            - %kernel.environment%
        calls:
            - [setLogger, [@ongr_task_messenger_logger]]
            - [setEnabled, [%ongr_task_messenger.task_publisher.amqp.enabled%]]
        tags:
            - { name: ongr_task_messenger.task_publisher }

    ongr_task_messenger.beanstalkd_connection_factory:
        class: %ongr_task_messenger.connection_factory.class%
        arguments:
            - %ongr_task_messenger.beanstalkd_connection.class%
            - %ongr_task_messenger.beanstalkd_connection.host%
            - %ongr_task_messenger.beanstalkd_connection.port%
    ongr_task_messenger.task_publisher.beanstalkd:
        class: %ongr_task_messenger.task_publisher.beanstalkd.class%
        arguments:
            - @ongr_task_messenger.beanstalkd_connection_factory
            - %kernel.environment%
        calls:
            - [setLogger, [@ongr_task_messenger_logger]]
            - [setEnabled, [%ongr_task_messenger.task_publisher.beanstalkd.enabled%]]
        tags:
            - { name: ongr_task_messenger.task_publisher }

    ongr_task_messenger.sync_task_complete_listener:
        class: %ongr_task_messenger.sync_task_complete_listener.class%
        tags:
            - { name: kernel.event_listener, event: ongr_connections.sync_task_complete, method: handleEvent }

    ongr_task_messenger_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [ongrTaskMessenger]
        calls:
            - [pushHandler, [@ongr_task_messenger_logger_handler]]

    ongr_task_messenger_logger_handler:
        class: Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/%kernel.environment%_task_messenger.log, %ongr_connections.log_level%]
